### ISSUE TITLE
Add full unit to `v`s, as in max-h-100v

### ISSUE THREAD

**Issue by acstll** [acstll/deprecated-css#2]
Sometimes you could mix axis, you could do:

```css
.max-w-100vh { max-width: 100vh; }
```
