### ISSUE TITLE
Helper to hide input

### ISSUE THREAD

**Issue by acstll** [acstll/deprecated-css#6]
To keep it focusable https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

```css
.h-hide-input-responsibly {
  width: 0.1px;
  height: 0.1px;
  opacity: 0;
  overflow: hidden;
  position: absolute;
  z-index: -1;
}
```
